In [1]:
import pandas as pd
import numpy as np
import regex as re
from tqdm import tqdm
from collections import defaultdict
from mlxtend.preprocessing import TransactionEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score
from mlxtend.frequent_patterns import fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [2]:
df = pd.read_csv(r'D:\Download\doc\SK_WIDIASIH\dataset_kompas\databersih\data_lokasiSMOTE_finalFPG.csv')

In [3]:
df.head()

,judul_berita,isi_berita,text_clean,label_kriminal,label_krim_gabungan,jenis_kriminal,prediksi_jenis_dt,motif_kejahatan,prediksi_motif_dt,hubungan_pelaku_korban,prediksi_hubungan_dt,karakteristik_kejahatan,prediksi_karakteristik_dt,waktu,prediksi_waktu_dt,lokasi,prediksi_lokasi_dt
0,Bocah yang Jasadnya Terbungkus Sarung Tewas Di...,"JAKARTA, KOMPAS.com - Pasangan pengemis bernam...",pasangan pengemis bernama sinta dewi 22 aidil ...,True,1,Pembunuhan,Pembunuhan,"Dendam, Emosi & Konflik","Dendam, Emosi & Konflik",Saling Kenal,Saling Kenal,Impulsif/Spontan,Impulsif/Spontan,Malam/Dini Hari,Malam/Dini Hari,Area Komersial,Area Komersial
1,Orangtua Bocah Tewas dalam Sarung Sering Aniay...,"JAKARTA, KOMPAS.com - Sinta Dewi (22) dan Aidi...",sinta dewi 22 aidil zacky rahman 19 pengemis d...,True,1,Penganiayaan & Kekerasan,Penganiayaan & Kekerasan,"Dendam, Emosi & Konflik","Dendam, Emosi & Konflik",Tidak Kenal/Tidak Diketahui,Tidak Kenal/Tidak Diketahui,Premeditasi/Terencana,Premeditasi/Terencana,Malam/Dini Hari,Malam/Dini Hari,Area Komersial,Area Komersial
2,Orangtua Bocah Tewas dalam Sarung Aniaya Anakn...,"JAKARTA, KOMPAS.com - Dua pengemis bernama Sin...",pengemis bernama sinta dewi 22 aidil zacky rah...,True,1,Pembunuhan,Penganiayaan & Kekerasan,"Dendam, Emosi & Konflik","Dendam, Emosi & Konflik",Tidak Kenal/Tidak Diketahui,Tidak Kenal/Tidak Diketahui,Impulsif/Spontan,Impulsif/Spontan,Malam/Dini Hari,Malam/Dini Hari,Area Komersial,Area Komersial
3,Orangtua Bocah Tewas Terbungkus Sarung di Beka...,"JAKARTA, KOMPAS.com - Balita berinisial RMR (3...",balita berinisial rmr 3 ditemukan tewas terbun...,True,1,Penganiayaan & Kekerasan,Penganiayaan & Kekerasan,"Dendam, Emosi & Konflik","Dendam, Emosi & Konflik",Saling Kenal,Saling Kenal,Impulsif/Spontan,Impulsif/Spontan,Malam/Dini Hari,Malam/Dini Hari,Area Komersial,Area Komersial
4,"Motif Orangtua Bunuh Anak di Bekasi, Emosi kar...","JAKARTA, KOMPAS.com - Polisi mengungkapkan, or...",polisi orangtua bernama sinta dewi 22 aidil za...,True,1,Pembunuhan,Pembunuhan,"Dendam, Emosi & Konflik","Dendam, Emosi & Konflik",Tidak Kenal/Tidak Diketahui,Tidak Kenal/Tidak Diketahui,Impulsif/Spontan,Impulsif/Spontan,Tidak Teridentifikasi,Tidak Teridentifikasi,Area Komersial,Area Komersial

# Data Cek

In [4]:
print("Jumlah baris data:")
jumlah_baris = len(df)
print(f"   Total baris data: {jumlah_baris}")

Jumlah baris data:
   Total baris data: 59141

In [5]:
jumlah_duplikasi = df.duplicated().sum()
print("Cek data duplikasi:")
print(f"   Jumlah baris duplikat: {jumlah_duplikasi}")

Cek data duplikasi:
   Jumlah baris duplikat: 0

In [6]:
print("Cek data kosong (Missing Values):")
data_kosong = df.isnull().sum()
print(data_kosong)

Cek data kosong (Missing Values):
judul_berita                 0
isi_berita                   0
text_clean                   0
label_kriminal               0
label_krim_gabungan          0
jenis_kriminal               0
prediksi_jenis_dt            0
motif_kejahatan              0
prediksi_motif_dt            0
hubungan_pelaku_korban       0
prediksi_hubungan_dt         0
karakteristik_kejahatan      0
prediksi_karakteristik_dt    0
waktu                        0
prediksi_waktu_dt            0
lokasi                       0
prediksi_lokasi_dt           0
dtype: int64

# Fp-Growth

In [7]:
cols_dt = [
    'prediksi_jenis_dt',
    'prediksi_motif_dt',
    'prediksi_hubungan_dt',
    'prediksi_karakteristik_dt',
    'prediksi_waktu_dt',
    'prediksi_lokasi_dt',
]
df_fpg = df[cols_dt].copy()

for col in cols_dt:
  clean_name = col.replace('prediksi_', '').replace('_dt', '')
  df_fpg[col] = clean_name + ': ' + df_fpg[col].astype(str)

df_encoded = pd.get_dummies(df_fpg, prefix='', prefix_sep='', dtype=int)
print('Data siap! Ukuran matriks:', df_encoded.shape)
df_encoded.head()

Data siap! Ukuran matriks: (59141, 26)

,jenis: Kejahatan Seksual dan Asusila,jenis: Kejahatan Siber,jenis: Narkotika,jenis: Pembunuhan,jenis: Pencurian & Perampokan,jenis: Penganiayaan & Kekerasan,jenis: Penipuan & Ekonomi,motif: Asmara & Kejahatan Seksual,"motif: Dendam, Emosi & Konflik",motif: Ekonomi & Harta Benda,...,waktu: Pagi Hari,waktu: Siang/Sore,waktu: Tidak Teridentifikasi,lokasi: Area Institusi/Kerja,lokasi: Area Komersial,lokasi: Area Privat (Hunian),lokasi: Area Publik (Umum),lokasi: Area Terbuka/Alam,lokasi: Ruang Digital/Siber,lokasi: Tidak Teridentifikasi
0,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0,1,0,...,0,0,1,0,1,0,0,0,0,0

In [8]:
support_candidates = [0.001, 0.01, 0.02, 0.03, 0.05, 0.08, 0.10, 0.15, 0.20]
summary_support = []

for sup in support_candidates:
    itemsets = fpgrowth(df_encoded, min_support=sup, use_colnames=True)

    itemsets_len_6 = itemsets[itemsets['itemsets'].apply(lambda x: len(x) == 6)]
    summary_support.append({
        'Min Support': sup,
        'Persentase Data': f'{sup*100:g}%',
        'Total Frequent Itemsets': len(itemsets),
        'Jumlah Pola 6 Variabel': len(itemsets_len_6)  
    })

df_summary = pd.DataFrame(summary_support)
display(df_summary)

C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,Min Support,Persentase Data,Total Frequent Itemsets,Jumlah Pola 6 Variabel
0,0.001,0.1%,4669,212
1,0.010,1%,1258,9
2,0.020,2%,666,2
3,0.030,3%,440,1
4,0.050,5%,249,0
5,0.080,8%,124,0
6,0.100,10%,85,0
7,0.150,15%,41,0
8,0.200,20%,21,0

# Percobaan Labeling Manual

In [9]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

frequent_itemsets = fpgrowth(df_encoded, min_support=0.01, use_colnames=True)
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.85)

rules_filtered = rules[rules['lift'] > 2].copy()

rules_filtered['jumlah_variabel'] = rules_filtered.apply( lambda r: len(r['antecedents'] | r['consequents']), axis=1)

rules_flexible = rules_filtered[rules_filtered['jumlah_variabel'] >= 2].copy()

rules_flexible['antecedents_str'] = rules_flexible['antecedents'].apply(lambda x: ', '.join(list(x)))
rules_flexible['consequents_str'] = rules_flexible['consequents'].apply(lambda x: ', '.join(list(x)))

rules_flexible = rules_flexible.sort_values(by=['jumlah_variabel', 'confidence', 'lift'],ascending=[False, False, False],)

print( f' Ditemukan {len(rules_flexible)} aturan asosiasi).\n')
display(
    rules_flexible[[
        'jumlah_variabel',
        'antecedents_str',
        'consequents_str',
        'support',
        'confidence',
        'lift',
    ]]
)

C:\Users\Java Computer\anaconda3\envs\tensorflow\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

 Ditemukan 134 aturan asosiasi).

,jumlah_variabel,antecedents_str,consequents_str,support,confidence,lift
341,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.035221,0.993324,2.080910
351,6,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi, hubungan: Saling Kenal",motif: Ekonomi & Harta Benda,0.012665,0.992053,2.078248
384,6,"lokasi: Ruang Digital/Siber, jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.013070,0.985969,2.065503
254,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi, lokasi: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.010264,0.983793,2.060943
63,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi, lokasi: Area Komersial",motif: Ekonomi & Harta Benda,0.016097,0.982456,2.058143
342,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.035221,0.981159,2.211637
352,6,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.012665,0.973992,2.195482
255,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Tidak Teridentifikasi, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.010264,0.972756,2.192697
385,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Ruang Digital/Siber, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.013070,0.972327,2.191729
64,6,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Komersial, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.016097,0.969450,2.185244
321,6,"karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi, jenis: Kejahatan Seksual dan Asusila, hubungan: Saling Kenal",motif: Asmara & Kejahatan Seksual,0.014322,0.915676,4.753685
320,6,"waktu: Tidak Teridentifikasi, lokasi: Area Institusi/Kerja, karakteristik: Premeditasi/Terencana, motif: Asmara & Kejahatan Seksual, hubungan: Saling Kenal",jenis: Kejahatan Seksual dan Asusila,0.014322,0.885057,5.185574
402,6,"lokasi: Area Privat (Hunian), karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi, jenis: Kejahatan Seksual dan Asusila, hubungan: Saling Kenal",motif: Asmara & Kejahatan Seksual,0.020155,0.877761,4.556855
336,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja",motif: Ekonomi & Harta Benda,0.045586,0.994100,2.082536
331,5,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.047886,0.992987,2.080205
338,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.035644,0.992935,2.080094
346,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja",motif: Ekonomi & Harta Benda,0.016689,0.990964,2.075966
469,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, waktu: Malam/Dini Hari, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.013848,0.990326,2.074631
348,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.012851,0.988296,2.070378
423,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.097614,0.986669,2.066969
379,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Ruang Digital/Siber, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.015539,0.986052,2.065675
252,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Tidak Teridentifikasi, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.010382,0.983974,2.061324
58,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, lokasi: Area Komersial",motif: Ekonomi & Harta Benda,0.021728,0.983920,2.061211
382,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Ruang Digital/Siber, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.013223,0.983648,2.060640
249,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, lokasi: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.012969,0.983333,2.059981
48,5,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Komersial, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.023537,0.983051,2.059389
374,5,"jenis: Penipuan & Ekonomi, lokasi: Ruang Digital/Siber, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.017129,0.982541,2.058321
197,5,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Publik (Umum), waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.011194,0.982196,2.057598
61,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Komersial, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.016300,0.981670,2.056496
459,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.041494,0.981600,2.056350
124,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, waktu: Siang/Sore",motif: Ekonomi & Harta Benda,0.011667,0.981508,2.056157
337,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Institusi/Kerja","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.045586,0.981434,2.212258
433,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, lokasi: Area Privat (Hunian)",motif: Ekonomi & Harta Benda,0.013933,0.980952,2.054993
439,5,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Privat (Hunian), waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.017923,0.980574,2.054199
202,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana, lokasi: Area Publik (Umum)",motif: Ekonomi & Harta Benda,0.010855,0.980153,2.053318
332,5,"jenis: Penipuan & Ekonomi, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.047886,0.979253,2.207341
444,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, karakteristik: Premeditasi/Terencana, lokasi: Area Privat (Hunian)",motif: Ekonomi & Harta Benda,0.011887,0.979109,2.051130
244,5,"jenis: Penipuan & Ekonomi, lokasi: Tidak Teridentifikasi, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.013645,0.974638,2.041764
53,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, karakteristik: Premeditasi/Terencana, lokasi: Area Komersial",motif: Ekonomi & Harta Benda,0.010653,0.972222,2.036704
424,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.097614,0.971558,2.189996
347,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Institusi/Kerja","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.016689,0.969548,2.185465
440,5,"jenis: Penipuan & Ekonomi, lokasi: Area Privat (Hunian), waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.017923,0.968921,2.184052
250,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.012969,0.968434,2.182954
380,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Ruang Digital/Siber","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.015539,0.968388,2.182849
375,5,"jenis: Penipuan & Ekonomi, lokasi: Ruang Digital/Siber, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.017129,0.967526,2.180908
434,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Privat (Hunian)","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.013933,0.967136,2.180028
59,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Komersial","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.021728,0.964715,2.174570
470,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, waktu: Malam/Dini Hari","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.013848,0.963529,2.171898
49,5,"jenis: Penipuan & Ekonomi, lokasi: Area Komersial, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.023537,0.961990,2.168429
245,5,"jenis: Penipuan & Ekonomi, lokasi: Tidak Teridentifikasi, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.013645,0.960714,2.165553
460,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.041494,0.960094,2.164154
125,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, waktu: Siang/Sore","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.011667,0.958333,2.160186
445,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Privat (Hunian)","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.011887,0.957766,2.158906
198,5,"jenis: Penipuan & Ekonomi, lokasi: Area Publik (Umum), waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.011194,0.949785,2.140916
54,5,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Komersial","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.010653,0.940299,2.119533
203,5,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Publik (Umum)","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.010855,0.937226,2.112608
318,5,"hubungan: Saling Kenal, jenis: Kejahatan Seksual dan Asusila, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Asmara & Kejahatan Seksual,0.016215,0.917703,4.764211
309,5,"hubungan: Saling Kenal, jenis: Kejahatan Seksual dan Asusila, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja",motif: Asmara & Kejahatan Seksual,0.019699,0.908028,4.713982
315,5,"jenis: Kejahatan Seksual dan Asusila, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Asmara & Kejahatan Seksual,0.019969,0.884644,4.592586
228,5,"hubungan: Tidak Kenal/Tidak Diketahui, motif: Narkotika & Alkohol, karakteristik: Premeditasi/Terencana, lokasi: Tidak Teridentifikasi",jenis: Narkotika,0.012293,0.882282,8.611819
314,5,"karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja, motif: Asmara & Kejahatan Seksual, waktu: Tidak Teridentifikasi",jenis: Kejahatan Seksual dan Asusila,0.019969,0.881343,5.163812
401,5,"hubungan: Saling Kenal, jenis: Kejahatan Seksual dan Asusila, lokasi: Area Privat (Hunian), waktu: Tidak Teridentifikasi",motif: Asmara & Kejahatan Seksual,0.023791,0.876090,4.548176
317,5,"hubungan: Saling Kenal, lokasi: Area Institusi/Kerja, motif: Asmara & Kejahatan Seksual, waktu: Tidak Teridentifikasi",jenis: Kejahatan Seksual dan Asusila,0.016215,0.859319,5.034772
405,5,"hubungan: Saling Kenal, jenis: Kejahatan Seksual dan Asusila, karakteristik: Premeditasi/Terencana, lokasi: Area Privat (Hunian)",motif: Asmara & Kejahatan Seksual,0.036557,0.857596,4.452168
398,5,"hubungan: Saling Kenal, jenis: Kejahatan Seksual dan Asusila, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Asmara & Kejahatan Seksual,0.048596,0.853832,4.432629
308,5,"hubungan: Saling Kenal, karakteristik: Premeditasi/Terencana, motif: Asmara & Kejahatan Seksual, lokasi: Area Institusi/Kerja",jenis: Kejahatan Seksual dan Asusila,0.019699,0.852231,4.993244
333,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Institusi/Kerja",motif: Ekonomi & Harta Benda,0.046144,0.993447,2.081169
326,4,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja",motif: Ekonomi & Harta Benda,0.062275,0.993258,2.080772
328,4,"jenis: Penipuan & Ekonomi, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.048494,0.991701,2.077511
343,4,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Institusi/Kerja",motif: Ekonomi & Harta Benda,0.017010,0.988212,2.070201
418,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.128016,0.986964,2.067586
420,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.099035,0.985695,2.064928
449,4,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.139108,0.985151,2.063790
466,4,"jenis: Penipuan & Ekonomi, waktu: Malam/Dini Hari, hubungan: Tidak Kenal/Tidak Diketahui",motif: Ekonomi & Harta Benda,0.014153,0.984706,2.062856
369,4,"jenis: Penipuan & Ekonomi, lokasi: Ruang Digital/Siber, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.020595,0.983845,2.061052
247,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.013172,0.983586,2.060510
376,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Ruang Digital/Siber",motif: Ekonomi & Harta Benda,0.015776,0.983140,2.059576
464,4,"jenis: Penipuan & Ekonomi, waktu: Malam/Dini Hari, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.020324,0.982829,2.058924
194,4,"jenis: Penipuan & Ekonomi, lokasi: Area Publik (Umum), waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.011566,0.981349,2.055823
55,4,"lokasi: Area Komersial, hubungan: Tidak Kenal/Tidak Diketahui, jenis: Penipuan & Ekonomi",motif: Ekonomi & Harta Benda,0.022100,0.981231,2.055577
121,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, waktu: Siang/Sore",motif: Ekonomi & Harta Benda,0.011938,0.980556,2.054162
119,4,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, waktu: Siang/Sore",motif: Ekonomi & Harta Benda,0.017687,0.980319,2.053665
428,4,"jenis: Penipuan & Ekonomi, lokasi: Area Privat (Hunian), karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.025820,0.980103,2.053213
43,4,"lokasi: Area Komersial, jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.032380,0.980041,2.053084
372,4,"jenis: Penipuan & Ekonomi, lokasi: Ruang Digital/Siber, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.017348,0.979943,2.052878
327,4,"jenis: Penipuan & Ekonomi, lokasi: Area Institusi/Kerja","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.062275,0.978220,2.205013
199,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Publik (Umum)",motif: Ekonomi & Harta Benda,0.011329,0.978102,2.049022
192,4,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Area Publik (Umum)",motif: Ekonomi & Harta Benda,0.016587,0.978066,2.048946
45,4,"lokasi: Area Komersial, jenis: Penipuan & Ekonomi, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.023926,0.977885,2.048568
454,4,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, karakteristik: Premeditasi/Terencana",motif: Ekonomi & Harta Benda,0.056813,0.977881,2.048559
431,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui, lokasi: Area Privat (Hunian)",motif: Ekonomi & Harta Benda,0.014085,0.977700,2.048179
437,4,"jenis: Penipuan & Ekonomi, lokasi: Area Privat (Hunian), waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.018075,0.977148,2.047023
456,4,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.042204,0.976526,2.045720
242,4,"jenis: Penipuan & Ekonomi, lokasi: Tidak Teridentifikasi, waktu: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.013848,0.975000,2.042523
239,4,"jenis: Penipuan & Ekonomi, karakteristik: Premeditasi/Terencana, lokasi: Tidak Teridentifikasi",motif: Ekonomi & Harta Benda,0.017196,0.974138,2.040717
442,4,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal, lokasi: Area Privat (Hunian)",motif: Ekonomi & Harta Benda,0.012090,0.974114,2.040668
419,4,"jenis: Penipuan & Ekonomi, hubungan: Tidak Kenal/Tidak Diketahui","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.128016,0.969026,2.184288
450,4,"jenis: Penipuan & Ekonomi, waktu: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.139108,0.968110,2.182224
370,4,"jenis: Penipuan & Ekonomi, lokasi: Ruang Digital/Siber","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.020595,0.965900,2.177242
429,4,"jenis: Penipuan & Ekonomi, lokasi: Area Privat (Hunian)","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.025820,0.962799,2.170253
50,4,"lokasi: Area Komersial, jenis: Penipuan & Ekonomi, hubungan: Saling Kenal",motif: Ekonomi & Harta Benda,0.010889,0.961194,2.013601
465,4,"jenis: Penipuan & Ekonomi, waktu: Malam/Dini Hari","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.020324,0.957769,2.158913
240,4,"jenis: Penipuan & Ekonomi, lokasi: Tidak Teridentifikasi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.017196,0.956726,2.156563
44,4,"lokasi: Area Komersial, jenis: Penipuan & Ekonomi","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.032380,0.956543,2.156151
455,4,"jenis: Penipuan & Ekonomi, hubungan: Saling Kenal","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.056813,0.954274,2.151036
120,4,"jenis: Penipuan & Ekonomi, waktu: Siang/Sore","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.017687,0.950909,2.143451
193,4,"jenis: Penipuan & Ekonomi, lokasi: Area Publik (Umum)","motif: Ekonomi & Harta Benda, karakteristik: Premeditasi/Terencana",0.016587,0.942363,2.124187
306,4,"jenis: Kejahatan Seksual dan Asusila, hubungan: Saling Kenal, lokasi: Area Institusi/Kerja",motif: Asmara & Kejahatan Seksual,0.023013,0.907939,4.713518
312,4,"jenis: Kejahatan Seksual dan Asusila, lokasi: Area Institusi/Kerja, waktu: Tidak Teridentifikasi",motif: Asmara & Kejahatan Seksual,0.022455,0.888294,4.611536
303,4,"jenis: Kejahatan Seksual dan Asusila, karakteristik: Premeditasi/Terencana, lokasi: Area Institusi/Kerja",motif: Asmara & Kejahatan Seksual,0.027257,0.883288,4.585544